# configs/config.yaml

# Data configuration
data:
  split_folder_name: "split_2000"
  image_size: 256 # Used for resizing images
  use_ridgelet: false
  augmentations:
    rand_flip_prob: 0.5
    rand_affine_prob: 0.5
    rotate_range: 0.1
    scale_range: 0.1

# Dataloader configuration
dataloader:
  batch_size: 32
  num_workers: 4

# Model configuration
model:
  base_model: "resnet18" # Or another model name your FractureDetector supports

# Training configuration
training:
  optimizer: "Adam" # Can be "Adam" or "SGD", for example
  epochs: 50
  learning_rate: 0.001
  weight_decay: 1e-5
  early_stopping_patience: 10 # Number of epochs to wait for improvement before stopping
  output_model_name: "best_model.pth" # Filename for the saved model
  loss:
    name: "FocalLoss" # Options: "FocalLoss", "BCEWithLogitsLoss"
    gamma: 2.0
    alpha: null # Or a value like 0.75
  scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 5

wandb:
  enabled: true
  project: "MIMIC_CXR_Fracture_Detection"
  entity: "your-wandb-username"