# configs/config.yaml

# The main pathology to target for classification (e.g., "Cardiomegaly", "Fracture", "Edema")
pathology: "Cardiomegaly"

# Data configuration
data:
  train_size: 80000
  image_size: 256 # Used for resizing images
  transform_name: null # Can be 'wavelet', 'ridgelet', or null
  persistent_cache_dir: "/path/to/your/disk/cache"
  transform_threshold_ratio: 0.1 # Parameter for applicable transforms
  
  transform_params:
    wavelet:
      wavelet_name: "haar" # Name of the wavelet to use, e.g., 'haar', 'db1', etc.
      # Number of wavelet decomposition levels. Set to null or 0 for maximum.
      levels: 3 
      # If true, concatenates the original image with the wavelet channels
      input_original_image: false 
  augmentations:
    rand_flip_prob: 0.5
    rand_affine_prob: 0.5
    rotate_range: 0.1
    scale_range: 0.1

# Dataloader configuration
dataloader:
  batch_size: 32
  num_workers: 4

# Model configuration
model:
  base_model: "resnet18" # Or another model name PathologyDetector supports

# Training configuration
training:
  optimizer: "Adam" # Can be "Adam" or "SGD", for example
  epochs: 50
  ram_cache_rate: 1
  learning_rate: 0.001
  weight_decay: 1e-5
  early_stopping_patience: 10 # Number of epochs to wait for improvement before stopping
  output_model_name: "best_model.pth" # Filename for the saved model
  loss:
    name: "FocalLoss" # Options: "FocalLoss", "BCEWithLogitsLoss"
    gamma: 2.0
    alpha: null # Or a value like 0.75
  scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 5

wandb:
  enabled: true
  project: "MIMIC_CXR_Fracture_Detection"
  entity: "your-wandb-username"